Fjerner litt bygg brukt i ft-kalkulus (#2)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,144 +1,95 @@
-name: Bygg og deploy
-
+name: "Bygg og deploy"
 on:
   push:
     branches:
-      - master
+      - '**'
     paths-ignore:
       - '**.md'
       - '**.MD'
       - '.gitignore'
+      - '.editorconfig'
+      - '.java-version'
+      - '.gitattributes'
       - 'LICENSE'
       - 'CODEOWNERS'
-      - 'dokumentasjon/**'
-      - 'lokalutvikling/**'
+      - 'docs/**'
+      - '.oracle/**'
+      - '.github/*.yml'
 
-  schedule:
-    - cron: '0 4 * * 1'
-
-env:
-  IMAGE_BASE_CR: ghcr.io/${{ github.repository }}
 jobs:
-  build:
+  build-app:
+    name: Build
     permissions:
       contents: read
-      issues: write
       packages: write
-    runs-on: ubuntu-latest
-    services:
-      postgres:
-        image: postgres:12
-        env:
-          POSTGRES_USER: ftkalkulus_unit
-          POSTGRES_PASSWORD: ftkalkulus_unit
-          POSTGRES_DB: ftkalkulus_unit
-        ports:
-          - 5432:5432
-        # needed because the postgres container does not provide a healthcheck
-        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
+      id-token: write
+    uses: navikt/fp-gha-workflows/.github/workflows/build-app-postgres.yml@main
+    with:
+      postgres-user: ftkalkulus_unit # TODO: endre til fpkalkulus_unit + resten av kodebasen
+      build-image: ${{ github.ref_name == 'master' }} # default: true
+      push-image: ${{ github.ref_name == 'master' }} # default: false
+    secrets: inherit
 
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-java@v4
-        with:
-          java-version: '21'
-          distribution: 'temurin'
-          cache: 'maven'
-
-      - name: Generer tag
-        run: |
-          echo "TAG=$(expr $(date +%Y%m%d%H%M%S))-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
-
-      - name: Build artifacts & deploy
-        shell: bash
-        run: |
-          echo "Building artifacts $(echo $GITHUB_SHA | cut -c1-7)"
-          mvn verify --quiet -e --settings .github/.m2/settings.xml --batch-mode -DtrimStackTrace=false --file pom.xml -Drevision= -Dchangelist= -Dsha1=$TAG -Dfile.encoding=UTF-8
-        env:
-          TZ: "Europe/Oslo"
-          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}
-          GH_ACCESS_TOKEN: ${{ secrets.READER_TOKEN }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          DATASOURCE_HOST: localhost
-          DATASOURCE_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
-
-      - name: Bygg og push docker-image
-        run: |
-          docker build --pull --tag ${IMAGE_BASE_CR}:${TAG} --tag ${IMAGE_BASE_CR}:latest .
-          echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username "x-access-token" --password-stdin ghcr.io
-          docker push ${IMAGE_BASE_CR}:${TAG}
-          docker push ${IMAGE_BASE_CR}:latest
-
-      - name: Lukk gamle issues
-        uses: actions/github-script@v7
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            github.rest.issues.listForRepo({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              state: 'open',
-              labels: ['deployment']
-            }).then(response => {
-              response.data.forEach(issue => {
-                github.rest.issues.update({
-                  owner: context.repo.owner,
-                  repo: context.repo.repo,
-                  issue_number: issue.number,
-                  state: 'closed'
-                });
-              });
-            });
-
-      -  name: Opprett deployment issue
-         id: createdeployissue
-         if: success()
-         uses: actions/github-script@v7
-         with:
-           github-token: ${{secrets.GITHUB_TOKEN}}
-           script: |
-               github.rest.issues.create( {
-                 owner: context.issue.owner,
-                 repo: context.issue.repo,
-                 labels: ['deployment'],
-                 title: 'Deploy av ${{ env.TAG }}',
-                 body: '${{ github.sha }}'})
-               .then(response => {
-                       core.setOutput('number', response.data.number);
-                });
-
-      - uses: navikt/github-app-token-generator@v1
-        id: get-token
-        with:
-          private-key: ${{ secrets.FP_PRIVATE_KEY }}
-          app-id: ${{ secrets.FP_APP_ID }}
-
-      - name: Trigger kalkulus verdikjede test
-        if: success()
-        shell: bash
-        run: |
-          curl -XPOST -u "x-access-token:${{ steps.get-token.outputs.token }}" \
-          -H "Accept: application/vnd.github.everest-preview+json" \
-          -H "Content-Type: application/json" \
-          https://api.github.com/repos/navikt/ft-kalkulus-verdikjede/dispatches \
-          --data '{"event_type": "beregning-verdikjede",
-                   "client_payload": {
-                      "trigger": "${{ github.repository }}",
-                      "version": "${{ env.TAG }}",
-                      "image": "${{ env.IMAGE }}",
-                      "issue_number": "${{ steps.createdeployissue.outputs.number }}"
-                  }}'
-
-      - name: Trigger k9 verdikjede test
-        shell: bash
-        run: |
-          curl -XPOST -u "x-access-token:${{ steps.get-token.outputs.token }}" \
-          -H "Accept: application/vnd.github.v3+json" \
-          https://api.github.com/repos/navikt/k9-verdikjede/actions/workflows/build.yml/dispatches \
-          -d '{"ref":"master",
-                  "inputs":{
-                      "trigger": "${{ github.repository }}",
-                      "version": "${{ env.TAG }}",
-                      "issue_number": "${{ steps.createdeployissue.outputs.number }}"
-                  }}'
-
+# TODO: Legg ved i deploy
+#  fpsak-tester:
+#    name: Fpsak tester
+#    permissions:
+#      contents: read
+#      id-token: write
+#    if: github.ref_name == 'master'
+#    needs: build-app
+#    uses: navikt/fp-autotest/.github/workflows/autotest.yml@master
+#    with:
+#      build-version: ${{ needs.build-app.outputs.build-version }}
+#      test-suite: fpsak
+#    secrets: inherit
+#
+#  verdikjede-tester:
+#    name: Verdikjedetester
+#    permissions:
+#      contents: read
+#      id-token: write
+#    if: github.ref_name == 'master'
+#    needs: build-app
+#    uses: navikt/fp-autotest/.github/workflows/autotest.yml@master
+#    with:
+#      build-version: ${{ needs.build-app.outputs.build-version }}
+#      test-suite: verdikjede
+#    secrets: inherit
+#
+#  notify:
+#    name: Notify
+#    if: github.ref_name == 'master' && (success() || failure()) && !contains(needs.*.result, 'skipped')
+#    needs: [build-app, fpsak-tester, verdikjede-tester]
+#    uses: navikt/fp-autotest/.github/workflows/report-and-notify.yml@master
+#    with:
+#      fpsak: ${{ needs.fpsak-tester.outputs.resultat }}
+#      verdikjede: ${{ needs.verdikjede-tester.outputs.resultat }}
+#      build-version: ${{ needs.build-app.outputs.build-version }}
+#    secrets: inherit
+#
+#  deploy-dev:
+#    name: Deploy dev
+#    permissions:
+#      id-token: write
+#    if: github.ref_name == 'master'
+#    needs: [build-app, fpsak-tester, verdikjede-tester]
+#    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
+#    with:
+#      gar: true
+#      image: ${{ needs.build-app.outputs.build-version }}
+#      cluster: dev-fss
+#    secrets: inherit
+#
+#  deploy-prod:
+#    name: Deploy prod
+#    permissions:
+#      id-token: write
+#    if: github.ref_name == 'master'
+#    needs: [build-app, fpsak-tester, verdikjede-tester, deploy-dev]
+#    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
+#    with:
+#      gar: true
+#      image: ${{ needs.build-app.outputs.build-version }}
+#      cluster: prod-fss
+#    secrets: inherit
